{{- if and $.Values.server.enabled (eq $.Values.server.mode "standalone") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.componentname" (list . "server") }}
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    helm.sh/chart: {{ include "temporal.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  type: {{ .Values.server.frontend.service.type }}
  ports:
    - port: {{ .Values.server.frontend.service.port }}
      targetPort: rpc
      protocol: TCP
      name: grpc-rpc
  selector:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
---
{{- end }}